/**
 * Image loading placeholders for rendered article content.
 *
 * Feed HTML often embeds large images that load progressively or fail,
 * causing visible "flash" / layout shift. This transform runs in the same
 * position as the YouTube transform — i.e. BEFORE sanitization — so DOMPurify
 * only ever sees standard elements and attributes. We add `loading="lazy"`
 * and a marker class to every `<img>`; the reader then:
 *   - fades the image in once it has loaded (via capture-phase load/error
 *     events — no inline handlers in the sanitized HTML), and
 *   - shows a subtle shimmer placeholder behind it while it is transparent.
 *
 * Only plain feed `<img>` elements are touched; nothing already generated by
 * the YouTube pipeline is modified.
 */

const IMG_TAG_RE = /<img\b([^>]*?)(\/\s*>|>)/gi;

/** Add our marker class and native lazy-loading to a raw `<img>` tag. */
export function decorateImageTag(attrs: string, closer: string): string {
	// Trim so we never emit double spaces from the captured attrs chunk.
	const trimmed = attrs.trim();
	// Prepend our class to any existing class attribute (kept by DOMPurify).
	const decorated = trimmed.replace(
		/\bclass="([^"]*)"/i,
		(_m, cls: string) => `class="${cls} reader-img"`,
	);
	// Build the attribute list with single-space separation.
	const parts: string[] = [];
	if (decorated) parts.push(decorated);
	if (!/\bclass="/i.test(decorated)) parts.push('class="reader-img"');
	if (!/\bloading=/i.test(decorated)) parts.push('loading="lazy"');
	const ending = closer.trim() === "/>" ? " />" : ">";
	return `<img${parts.length ? ` ${parts.join(" ")}` : ""}${ending}`;
}

/** Wrap every plain feed `<img>` tag with a placeholder wrapper + class. */
export function transformImagesToPlaceholders(html: string): string {
	return html.replace(IMG_TAG_RE, (_m, attrs: string, closer: string) =>
		decorateImageTag(attrs, closer),
	);
}
