/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AsyncButton: typeof import('./src/components/AsyncButton.vue')['default']
    DeleteFeedDialog: typeof import('./src/components/DeleteFeedDialog.vue')['default']
    EntryList: typeof import('./src/components/EntryList.vue')['default']
    EntryListItem: typeof import('./src/components/EntryListItem.vue')['default']
    EntryListPane: typeof import('./src/components/EntryListPane.vue')['default']
    EntryReader: typeof import('./src/components/EntryReader.vue')['default']
    EntrySummary: typeof import('./src/components/EntrySummary.vue')['default']
    FeedDialog: typeof import('./src/components/FeedDialog.vue')['default']
    GithubMarkIcon: typeof import('./src/components/GithubMarkIcon.vue')['default']
    MobileBottomNav: typeof import('./src/components/MobileBottomNav.vue')['default']
    ReaderPane: typeof import('./src/components/ReaderPane.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./src/components/scroll-area/ScrollBar.vue')['default']
    SettingsDialog: typeof import('./src/components/SettingsDialog.vue')['default']
    SignOutDialog: typeof import('./src/components/SignOutDialog.vue')['default']
    UiBadge: typeof import('./src/components/UiBadge.vue')['default']
    UiButton: typeof import('./src/components/UiButton.vue')['default']
    UiInput: typeof import('./src/components/UiInput.vue')['default']
    UiSelect: typeof import('./src/components/select/UiSelect.vue')['default']
    UiSelectContent: typeof import('./src/components/select/UiSelectContent.vue')['default']
    UiSelectItem: typeof import('./src/components/select/UiSelectItem.vue')['default']
    UiSelectScrollDownButton: typeof import('./src/components/select/UiSelectScrollDownButton.vue')['default']
    UiSelectScrollUpButton: typeof import('./src/components/select/UiSelectScrollUpButton.vue')['default']
    UiSelectTrigger: typeof import('./src/components/select/UiSelectTrigger.vue')['default']
    UiSelectValue: typeof import('./src/components/select/UiSelectValue.vue')['default']
    UiSwitch: typeof import('./src/components/UiSwitch.vue')['default']
    UiTooltip: typeof import('./src/components/UiTooltip.vue')['default']
  }
}
